homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 50.6605716
  longitude: 3.1379015999999638
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages

  auth_providers:
  - type: legacy_api_password
    api_password: !secret http_password  
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
      - 127.0.0.1
      - ::1
      - 192.168.0.0/24
      - fd00::/8

logger:
  default: debug
  logs:
    homeassistant.components.remote.harmony: debug
    homeassistant.components.harmony.remote: debug
    aioharmony.harmonyclient: debug
    aioharmony.responsehandler: debug
    aioharmony.hubconnector: debug
    homeassistant.components.netatmo.climate: debug
    homeassistant.components.netatmo.camera: debug
    homeassistant.components.netatmo: debug
    # aioharmony.hubconnector: debug
    # requests.packages.urllib3.connectionpool: error # critical #for this item anything below error will not be logged
    # py.warnings: critical
    # volvooncall: debug
    # homeassistant.components.volvooncall: debug
    # homeassistant.components.influxdb: debug
    # homeassistant.components.image_processing: debug
    # homeassistant.components.sensor.influxdb: debug
    # homeassistant.components.device_tracker.bluetooth_le_tracker: debug
    # homeassistant.components.arlo: debug
    # homeassistant.components.display: debug
    # homeassistant.components.rfxtrx: debug
    homeassistant.components.teleinfo: debug
    teleinfo: debug
    # homeassistant.components.xiaomi_aqara: debug
    # homeassistant.components.binary_sensor.xiaomi_aqara: debug
    # homeassistant.components.sensor.xiaomi_aqara: debug
    # homeassistant.components.light.xiaomi_aqara: debug
    # homeassistant.components.switch.xiaomi_aqara: debug
    # the chatty ones
    homeassistant.components.influxdb.sensor: warning 
    influxdb.sensor: warning 
    kylin: debug

    # / the chatty ones

#  whitelist_external_dirs: 
#    - '/home/homeassistant/.homeassistant/downloads'
  
# Show links to resources in log and frontend
#introduction:

zone:
  - name: Work
    latitude: 50.6917
    longitude: 3.202308
    radius: 200
    icon: mdi:work

  # This will override the default home zone
  - name: Home
    latitude: 50.6605716
    longitude: 3.1379015999999638
    radius: 60
    icon: mdi:accountmultiple

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
  # to force custom components to load properly on ios
  # nb: can cause automation and script editor to crash
  javascript_version: latest

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  #  api_password: !secret http_password #replated by auth component
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
   base_url: !secret base_url 
   trusted_proxies: !secret trusted_proxies 
   use_x_forwarded_for: true
  #  ip_ban_enabled: true
   login_attempts_threshold: 10
  #  trusted_networks:
  #    - 127.0.0.1
  #    - ::1
  #    - 192.168.0.0/24
  #  # - fd00::/8#  
   # cors_allowed_origins:


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# discovery:
#
hassio:


# Recorder
recorder:
  purge_interval: 2
  purge_keep_days: 30
  db_url: !secret mariadb_connection_url

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
   exclude:
     entities:
       - sensor.time
       - sensor.time
       - sensor.hour
       - sensor.moon
       - sun.sun
       - sensor.dark_sky_daily_summary
       - sensor.dark_sky_hourly_summary
       - sensor.dark_sky_icon
       - sensor.dark_sky_summary
       - alarm_control_panel.arlo 
#   domains:
#     - switch
#     - updater
#  include:
#    domains:
#      - group
#      - automation
#      - sensor
#      - binary_sensor
#      - media_player
#      - switch
#
# View all events in a logbook
logbook: !include logbook.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml

rest_command: !include rest_command.yaml

influxdb:
  host: !secret influx_host
  port: 8086
  max_retries: 10
  include:
    domains:
      - sensor
      - binary_sensor
      - climate
      - switch
      - person
  # include:
  #   entities:
  #     - sensor.teleinfo_hchc
  #     - sensor.teleinfo_hchp
  #     - sensor.teleinfo_hhphc
  #     - sensor.teleinfo_iinst
  #     - sensor.teleinfo_imax
  #     - sensor.teleinfo_isousc
  #     - sensor.teleinfo_papp
  #     - sensor.teleinfo_ptec


# APC Battery
apcupsd:
  host: 192.168.0.27
  port: 3551

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# now in "harmony" package
# remote:
#   - platform: harmony
#     name: harmony hub
#     host: 192.168.0.29
#     activity: Regarder la TV

weather:
  # - platform: yweather
  - platform: darksky
    api_key: !secret darksky_api_key 
    mode: daily
    units: ca
    # language: fr
#    forecast:
#      - 1
#      - 2
#      - 3
#      - 4
#      - 5
#      - 6
#      - 7
    # monitored_conditions:
    #   - temperature
    #   - apparent_temperature
    #   - summary
    #   - icon
    #   - precip_probability


# Weather prediction

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    time_memory: 300
    language: 'fr'

# Cloud
cloud:

group: !include groups.yaml
# automation: !include automations.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml

sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml

media_player:
  - platform: squeezebox
    host: !secret squeezebox_host
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: panasonic_viera
    host: !secret panasonic_tv_host
  # Use the Python ADB implementation without authentication
  # - platform: androidtv
  #   name: Fire TV
  #   host: 192.168.0.44


cast:
  media_player:
    - host: !secret google_home_host


# camera:
#   - platform: foscam
#     ip: !secret foscam_ip
#     username: !secret foscam_username
#     password: !secret foscam_password
#   # - platform: arlo
#   #   ffmpeg_arguments: '-pred 1 -q:v 2'
#   # - platform: ffmpeg
#   #   name: DaFang3
#   #   input: !secret dafang_rtsp 
#   - platform: generic
#     name: DaFang3
#     still_image_url: !secret dafang_still_image_url
#     stream_source: !secret dafang_rtsp_url
#     verify_ssl: false
#     username: !secret dafang_username
#     password:  !secret dafang_password
#     authentication: basic
  






xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_gw1_key
      host: !secret xiaomi_aqara_gw1_host 
      mac: !secret xiaomi_aqara_gw1_mac
    - key: !secret xiaomi_aqara_gw2_key
      host: !secret xiaomi_aqara_gw2_host 
      mac: !secret xiaomi_aqara_gw2_mac


vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token



panel_iframe:
  # configurator:
  #   title: Configurator
  #   icon: mdi:wrench
  #   url: !secret panel_iframe_configurator_url 
  grafana:
    title: Grafana
    icon: mdi:chart-areaspline
    url: !secret panel_iframe_grafana_url
  grafana_power:
    title: Grafana - Power
    icon: mdi:flash-circle
    url: !secret panel_iframe_grafana_power_consumption
#  pihole:
#    title: Pi-hole
#    icon: mdi:block-helper
#    url: http://192.168.0.24/admin/index.php

#panel_custom:
#  - name: alarm
#    sidebar_title: Alarm
#    sidebar_icon: mdi:security-home
#    config:
#      alarmid: alarm_control_panel.home_alarm ## USE THE SAME ID AS USED IN YOUR ALARM.YAML


zwave:
   usb_path: /dev/ttyACM0
  #  device: /dev/serial/by-id/usb-0658_0200-if00
   network_key: !secret zwave_network_key 


rfxtrx:
   device: /dev/ttyUSB1
  #  device: /dev/serial/hoby-id/usb-RFXCOM_RFXtrx433_A1K5NSX-if00-port0
  #  debug: true
 
light:
  - platform: rfxtrx
    automatic_add: False
    signal_repetitions: 5

  #  used by lovelace-fullykiosk.js
  - platform: template
    lights:
      chuwi:
        turn_on:
        turn_off:
        set_level:

switch: !include switch.yaml



# device_tracker:
# #   - platform: owntracks_http
# #     max_gps_accuracy: 100
# #     # - platform: bluetooth_tracker
#   # - platform: bluetooth_le_tracker
#     # track_new_devices: true
#   - platform: bluetooth_tracker
#   - platform: ble_tracker

# - platform: icloud
#   username: !secret icloud_username
#   password: !secret icloud_password
  # - platform: nmap_tracker
  #   hosts:
  #           - 192.168.0.19
  #           - 192.168.0.32
  #   home_interval: 30
#  - platform: icloud2
#    username: !secret icloud_username
#    password: !secret icloud_password
#    account_name: pierreIcloud2
#    filter_devices: 'phone'

notify:
  - name: Telegram
    platform: telegram
    chat_id: !secret telegram_chat_id 
  - platform: ios

telegram_bot:
        #- platform: webhooks
  - platform: polling
    # jeedom
    #api_key: 307112869:AAGw8pNelwkZgaULYonS9f1_SBQLxIfnBN0
    api_key: !secret telegram_api_key 
    allowed_chat_ids:  
       - !secret telegram_chat_id 
# for webhooks mode only
    parse_mode: html
    # trusted_networks:
    #   - 192.168.0.0/16


google_assistant:
  project_id: !secret google_assistant_project_id
# client_id: !secret google_assistant_client_id
# access_token: !secret google_assistant_access_token
# agent_user_id: [a string to identify user]
  api_key: !secret google_assistant_api_key
#  expose_by_default: false
  exposed_domains:
#   - switch
    - light
#   - group
    - alarm
    - climate
    - media_player
#  entity_config:
#    switch.kitchen:
#      name: Custom Name for Google Assistant
#      aliases:
#        - bright lights
#        - entry lights
#    light.living_room:
#      expose: false
#      room: living room


      

ios: !include ios.yaml

# Example using a delay after start of Home Assistant
homekit: !include homekit.yaml



ffmpeg:
  # run_test: false

# arlo:
#   username: !secret arlo_username
#   password: !secret arlo_password


# display:
#   - platform: fully_kiosk
#     name: chuwi
#     host: !secret chuwi_host
#     password: !secret chuwi_password

# climate: !include climate.yaml
alert: !include alert.yaml
image_processing: !include image_processing.yaml
proximity: !include proximity.yaml

lovelace:
  mode: yaml


custom_updater:
  # mode: yaml
  show_installable: False # hide not-used custom stuff  
  track:
    - components
    - cards
    - python_scripts
  # card_urls:
  #   - https://raw.githubusercontent.com/sgttrs/lovelace-weather-card-chart/master/custom-updater.json
  #   - https://raw.githubusercontent.com/ljmerza/light-entity-card/master/custom_updater.json
    # - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

weblink: !include weblink.yaml
system_health:
# stream:


asuswrt:
  host: !secret asus_router_ip 
  username: !secret asus_router_username
  password: !secret asus_router_password
  # ssh_key: !secret asus_router_ssh_key 
  # sensors:
  #   - upload
  #   - download
  #   - upload_speed
  #   - download_speed