homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 50.6605716
  longitude: 3.1379015999999638
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  #  customize_glob: !include customize_glob.yaml

  # Customize entities matching a pattern
  customize_glob:
    'sensor.fibaro_system_fgd212_dimmer_2*':
      hidden: true
      homebridge_hidden: true
  #  "sensor.fibaro_system_fgd212_dimmer_2_alarm_level*":
  #    hidden: true
  #    homebridge_hidden: true
  #  "sensor.fibaro_system_fgd212_dimmer_2_alarm_type*":
  #    hidden: true
  #    homebridge_hidden: true
  #  "sensor.fibaro_system_fgd212_dimmer_2_exporting*":
  #    hidden: true
  #    homebridge_hidden: true
  #  "sensor.fibaro_system_fgd212_dimmer_2_heat*":
  #    hidden: true
  #    homebridge_hidden: true
  #  "sensor.fibaro_system_fgd212_dimmer_2_power_management*":
  #    hidden: true
  #    homebridge_hidden: true
  #  "sensor.fibaro_system_fgd212_dimmer_2_system*":
  #    hidden: true
  #    homebridge_hidden: true
    "sensor.fibaro_system_fgfs101_flood_sensor_alarm_type*":
      hidden: true
      homebridge_hidden: true
    "sensor.neo_coolcam_power_plug_12a_interval*":
      hidden: true
      homebridge_hidden: true
    "sensor.neo_coolcam_power_plug_12a_previous_reading*":
      hidden: true
      homebridge_hidden: true
    "sensor.qubino_zmnhjd1_flush_dimmer_pilot_wire_temperature":
      hidden: true
      homebridge_hidden: true
    "zwave.*":
      hidden: true
      homebridge_hidden: true
    "binary_sensor.qubino_zmnhjd1_flush_dimmer_pilot_wire_sensor*":
      hidden: true
      homebridge_hidden: true
    "sensor.*sourcenodeid*":
      hidden: true
      homebridge_hidden: true
  
logger:
# default: info
# logs:
#   homeassistant.components.teleinfo: debug
#    homeassistant.components.xiaomi_aqara: debug
#    homeassistant.components.binary_sensor.xiaomi_aqara: debug
#    homeassistant.components.sensor.xiaomi_aqara: debug
#    homeassistant.components.light.xiaomi_aqara: debug
#    homeassistant.components.switch.xiaomi_aqara: debug

#  whitelist_external_dirs: 
#    - '/home/homeassistant/.homeassistant/downloads'
  
#  customize_glob:
#    "sensor.humidity_*":
#      friendly_name: Humidity
#    "sensor.pressure_*":
#      friendly_name: Pression
#    "sensor.temperature_*":
#      friendly_name: Temperature
#    "sensor.illumination_*":
#      friendly_name: Illumination
#    "binary_sensor.switch_*":
#      friendly_name: Button

# Show links to resources in log and frontend
#introduction:

zone:
  - name: Work
    latitude: 50.6917
    longitude: 3.202308
    radius: 200
    icon: mdi:work

  # This will override the default home zone
  - name: Home
    latitude: 50.6605716
    longitude: 3.1379015999999638
    radius: 30
    icon: mdi:accountmultiple

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
   api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
   base_url: https://hassio.ourdouille.maison
   trusted_proxies: 192.168.0.27
   use_x_forwarded_for: true
   ip_ban_enabled: false
   login_attempts_threshold: 5
   cors_allowed_origins:
     - http://192.168.0.24:8234
     - http://hassio.ourdouille.maison:8234
     - https://hassio.ourdouille.maison

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# discovery:
#
hassio:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - sensor.time
      - sensor.hour
      - sensor.moon
#      - sensor.dark_sky_daily_summary
#      - sensor.dark_sky_hourly_summary
#      - sensor.dark_sky_icon
#      - sensor.dark_sky_summary
    domains:
      - switch
      - updater
#  include:
#    domains:
#      - group
#      - automation
#      - sensor
#      - binary_sensor
#      - media_player
#      - switch
#
# View all events in a logbook
logbook: !include logbook.yaml

influxdb:
  host: 192.168.0.28
#  include:
#    entities:
#      - sensor.teleinfo_hchc
#      - sensor.teleinfo_hchp
#      - sensor.teleinfo_hhphc
#      - sensor.teleinfo_iinst
#      - sensor.teleinfo_imax
#      - sensor.teleinfo_isousc
#      - sensor.teleinfo_papp
#      - sensor.teleinfo_ptec
#

# APC Battery
apcupsd:


# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

remote:
  - platform: harmony
    name: harmony hub
    host: 192.168.0.29
    activity: Regarder la TV

weather:
  - platform: darksky
    api_key: !secret darksky_api_key 
    units: ca
    language: fr
    monitored_conditions:
      - temperature
      - apparent_temperature
      - summary
      - icon
      - precip_probability


# Weather prediction

# Text to speech
tts:
  - platform: google
    cache: true
    time_memory: 300
    language: 'fr'

# Cloud
cloud:

group: !include groups.yaml
# automation: !include automations.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml

sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml

media_player:
  - platform: squeezebox
    host: !secret squeezebox_host
#  - platform: cast

cast:
        #  media_player:

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password 

camera:
  - platform: foscam
    ip: !secret foscam_ip
    username: !secret foscam_username
    password: !secret foscam_password
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_gw1_key
      host: !secret xiaomi_aqara_gw1_host 
      mac: !secret xiaomi_aqara_gw1_mac
    - key: !secret xiaomi_aqara_gw2_key
      host: !secret xiaomi_aqara_gw2_host 
      mac: !secret xiaomi_aqara_gw2_mac


vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token



panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://hassio.ourdouille.maison/configurat0r/
#  pihole:
#    title: Pi-hole
#    icon: mdi:block-helper
#    url: http://192.168.0.24/admin/index.php

#panel_custom:
#  - name: alarm
#    sidebar_title: Alarm
#    sidebar_icon: mdi:security-home
#    config:
#      alarmid: alarm_control_panel.home_alarm ## USE THE SAME ID AS USED IN YOUR ALARM.YAML


zwave:
   usb_path: /dev/ttyACM0
   network_key: !secret zwave_network_key 


rfxtrx:
   device: /dev/ttyUSB1
   #debug: true
   #
light:
  - platform: rfxtrx
#   automatic_add: True


switch: !include switch.yaml

device_tracker:
  - platform: owntracks_http
    max_gps_accuracy: 100
    # - platform: bluetooth_tracker
    # - platform: bluetooth_le_tracker
# - platform: icloud
#   username: !secret icloud_username
#   password: !secret icloud_password
  - platform: nmap_tracker
    hosts:
            - 192.168.0.19
            - 192.168.0.32
  - platform: icloud2
    username: !secret icloud_username
    password: !secret icloud_password
    account_name: pierreIcloud2
    filter_devices: 'phone'

notify:
  - name: Telegram
    platform: telegram
    chat_id: !secret telegram_chat_id 

telegram_bot:
        #- platform: webhooks
  - platform: polling
    # jeedom
    #api_key: 307112869:AAGw8pNelwkZgaULYonS9f1_SBQLxIfnBN0
    # hassio_ourdouille_bot
    api_key: !secret telegram_api_key 
    allowed_chat_ids:  
       - !secret telegram_chat_id 
# for webhooks mode only
    parse_mode: html
    trusted_networks:
      - 192.168.0.0/16


google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  # agent_user_id: [a string to identify user]
#  api_key: AIzaSyBVn9-a3C_V8jAiCWcipvBqZXII0ugRsQI
  api_key: !secret google_assistant_api_key
#  expose_by_default: false
  exposed_domains:
    - switch
    - light
    - group
#  entity_config:
#    switch.kitchen:
#      name: Custom Name for Google Assistant
#      aliases:
#        - bright lights
#        - entry lights
#    light.living_room:
#      expose: false
#      room: living room


      

ios:

# Example using a delay after start of Home Assistant
homekit:
  auto_start: False

# Example configuration.yaml entry
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    #code: 1234
    disarm_after_trigger: false
    # time to leave
    pending_time: 30
    # time to disarm
    delay_time: 20
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 60
      delay_time: 0
  - platform: arlo


input_select:
  # Current automation mode
  # Normal - normal day to day life, work etc.
  # On Vacation - nobody is at home for a long period of time
  # Have guests - we have guests staying over
  system_mode:
    name: House Mode
    options:
      - Normal
      - On vacation
      - Have guests
    initial: Normal

ffmpeg:

arlo:
  username: !secret arlo_username
  password: !secret arlo_password


