- id: arm_alarm_when_pierre_leaves
  alias: Arm alarm when Pierre leaves
  trigger:
  - entity_id: binary_sensor.pierre_is_home
    platform: state
    to: 'off'
  action:
  - data:
      message: Pierre est parti!
      title: Pierre leaves
    service: notify.telegram
#  - data: {}
#    service: alarm_control_panel.alarm_arm_away
- id: trigger_alarm_while_armed_away
  alias: Trigger alarm when armed away
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001ddb2d3
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d0001ab34c1
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d0001e163a1
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d0001b1cff9
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d0001ab34e1
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_trigger
- id: send_notification_when_alarm_triggered
  alias: Send notification when alarm triggered
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: triggered
  action:
  - service: script.presence_notifications_when_alarm_triggered
- alias: Telegram bot that reply pong to ping
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /ping
  action:
  - service: notify.telegram
    data:
      message: pong
  id: c9409bc577fc4f749688d33b1f7dfd9e

- id: disarm_alarm_when_pierre_is_back
  alias: Disarm alarm when Pierre is back home
  trigger:
  - entity_id: binary_sensor.pierre_is_home
    platform: state
    to: 'on'
  action:
  - data:
      message: Pierre est de retour!
      title: Pierre is back home
    service: notify.telegram
  - data: {}
    service: alarm_control_panel.alarm_disarm

