
- id: electricity_failure_notification
  alias: 'Electricity: Failure notification'
  trigger:
  - entity_id: sensor.ups_status
    platform: state
    from: 'ONLINE'
# condition:
  action:
  - service: notify.telegram
    data:
      title: Electricité
      message: |
        Coupure électrique! APC en statut: {{sensor.ups_status}}. Il reste {{  sensor.ups_time_left }}min. de batterie


- id: electricity_bill_daily
  alias: 'Electricity: Daily Bill'
  trigger:
    platform: time
    # When 'at' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    at: '08:00:00'
# condition:
  action:
  - service: notify.telegram
    data:
      title: Electricité
      message: |
        Hier, l'électricité a coûté <b> {{ states.sensor.elecbill_today_ttc.state |float | round(2) }}</b>€

- id: electricity_bill_weekly
  alias: 'Electricity: Weekly Bill'
  trigger:
    platform: time
    # When 'at' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    at: '08:00:00'
  condition:
    - condition: time
      weekday:
        - mon
  action:
  - service: notify.telegram
    data:
      title: Electricité
      message: |
        Cette semaine, l'électricité a coûté <b> {{ states.sensor.elecbill_last_week_ttc.state |float | round(2) }}</b>€

- id: electricity_bill_monthly
  alias: 'Electricity: Weekly Bill'
  trigger:
  - platform: template
    value_template: '{{ now().strftime("%d") == "01" }}'
  action:
  - service: notify.telegram
    data:
      title: Electricité
      message: |
        Ce mois-ci, l'électricité a coûté <b> {{ states.sensor.elecbill_last_month_ttc.state |float | round(2) }}</b>€





- id: electricity_monthly_report
  alias: 'Electricity: Monthly Report'
  trigger:
  - platform: template
    value_template: '{{ now().strftime("%d") == "01" }}'
# condition:
  action:
  - service: notify.telegram
    data:
      title: Electricité
      message: |
        Il est temps de déclarer la conso !
        HP: {{ '<b>{0}{1}{2}{3}{4}</b>.{5}{6}{7}'.format(*states.sensor.teleinfo_hchp.state) }}kWh
        HC: {{ '<b>{0}{1}{2}{3}{4}</b>.{5}{6}{7}'.format(*states.sensor.teleinfo_hchc.state) }}kWh
        https://clients.direct-energie.com/ma-conso/faire-mon-e-releve/
#       HP: {{ states.sensor.teleinfo_hchp.state  }}
#       HC: {{ states.sensor.teleinfo_hchc.state  }} 
#     message: Test
#  - service: tts.google_say
#    data:
#      entity_id: media_player.google_home__salon
#      message: "La place de parking vient de se libérer"





################################################
## Store meter readings at midnight so that power consumption per day can be caculated
################################################
- id: electricity_store_meter_readings_at_midnight
  alias: 'Electricity: store metrics at midnight'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.24hour_power_hp_consumption
        value: "{{ (((states.sensor.teleinfo_hchp.state  | float) - states('input_number.power_hp_meter_value_at_midnight') | float ) | round(3))}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.24hour_power_hc_consumption
        value: "{{ (((states.sensor.teleinfo_hchc.state  | float) - states('input_number.power_hc_meter_value_at_midnight') | float ) | round(3))}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.24hour_heat_consumption
        value: "{{ (((  state_attr('sensor.owl_180_energy_usage', 'Total usage') | float) - states('input_number.heat_meter_value_at_midnight') | float ) | round(3))}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.power_hp_meter_value_at_midnight
        value: "{{ states.sensor.teleinfo_hchp.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.power_hc_meter_value_at_midnight
        value: "{{ states.sensor.teleinfo_hchc.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.heat_meter_value_at_midnight
        value: "{{  state_attr('sensor.owl_180_energy_usage', 'Total usage') }}"





################################################################################################
## Tentative to guess which device is switched on
################################################################################################

- alias: 'Electricity: guess what ?'
  trigger:
    platform: state
    entity_id: sensor.derivative_teleinfo_papp
  action:
    service: notify.telegram
    data_template:
      message: >
        {% if states("sensor.derivative_teleinfo_papp")|float > 2700 and states("sensor.derivative_teleinfo_papp")|float< 2800 %}
        "{{ states.sensor.derivative_teleinfo_papp.state }} | Démarrage: ballon d'eau chaude ?"
        {% elif states("sensor.derivative_teleinfo_papp")|float > 2400 and states("sensor.derivative_teleinfo_papp")|float< 2500 %}
        "{{ states.sensor.derivative_teleinfo_papp.state }} | Démarrage: lave vaisselle ?"
        {% elif states("sensor.derivative_teleinfo_papp")|float > 630 and states("sensor.derivative_teleinfo_papp")|float< 650 %}
        "{{ states.sensor.derivative_teleinfo_papp.state }} | Démarrage: chauffage salle de douche ?"
        {% elif states("sensor.derivative_teleinfo_papp")|float > 1910 and states("sensor.derivative_teleinfo_papp")|float< 2050 %}
        "{{ states.sensor.derivative_teleinfo_papp.state }} | Démarrage: chauffage salon ?"
        {% elif states("sensor.derivative_teleinfo_papp")|float > 1240 and states("sensor.derivative_teleinfo_papp")|float< 1340 %}
        "{{ states.sensor.derivative_teleinfo_papp.state }} | Démarrage: chauffage chambre ?"
        {%endif%}

#{%else%}
#{{ states.sensor.derivative_teleinfo_papp.state |float round(2) }} | Quel appareil ?"
          
