- id: telegramCommandDisarmAlarm
  alias: 'Telegram bot answer to command: /alarm_disarm'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      data: /alarm_disarm
  action:
  - service: alarm_control_panel.alarm_disarm
  - service: notify.telegram
    data:
      message: Alarme désarmée

- id: telegramCallbackDisarmAlarm
  alias: 'Telegram bot answer to command: /disarm_alarm'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: /alarm_disarm
  action:
  - service: alarm_control_panel.alarm_disarm
  - service: notify.telegram
    data:
      message: Alarme désarmée


- id: telegramPresenceTriggered
  alias: 'Telegram bot answer to command: /presence_triggered_alarm'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      data: /cameras
  action:
  - service: script.telegram_snapshots_all_cameras

- alias: Telegram bot that reply pong to ping
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /ping
  action:
  - service: notify.telegram
    data:
      message: pong
  id: c9409bc577fc4f749688d33b1f7dfd9e


