################################################
## Packages / Host / Updates
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'alarm'

    ################################################
    ## Binary Sensor
    ################################################

    # binary_sensor.hass_update_available:
    #   <<: *customize
    #   friendly_name: 'Update Available Hass'
    #   device_class: problem

    ################################################
    ## Sensor
    ################################################

# https://github.com/twrecked/hass-aarlo
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    #code: 1234
    disarm_after_trigger: false
    # time to leave
    pending_time: 30
    # time to disarm
    delay_time: 20
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 60
      delay_time: 0
  
  # - platform: arlo
  #   home_mode_name: arm_home

  - platform: aarlo
    home_mode_name: arm_home
    away_mode_name: armed
    trigger_time: 30
    alarm_volume: 8

################################################
## Sensor
################################################

sensor:
  - platform: aarlo
    monitored_conditions:
    - last_capture
    - total_cameras
    - battery_level
    - captured_today
    - signal_strength
################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding

################################################
## Automation
################################################

automation:

  # Trigger (away)
  - id: trigger_alarm_while_armed_away
    alias: "Alarm: Trigger when armed away"
    trigger:
  #  - entity_id: binary_sensor.motion_detected
  #    platform: state
  #    to: 'on'
    - entity_id: group.perimeter_detectors
      platform: state
      to: 'on'
    - entity_id: group.motion_detectors
      platform: state
      to: 'on'
    condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
    action:
    - entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_trigger
    - entity_id: alarm_control_panel.aarlo_arlo
      service: alarm_control_panel.alarm_trigger
    - service: light.turn_on
      data:
        brightness: '100'
        color_name: red
        entity_id: light.gateway_light_7811dcb7afd1
    - service: light.turn_on
      data:
        brightness: '100'
        color_name: red
        entity_id: light.gateway_light_34ce008c1873


  # Trigger (home)
  - id: trigger_alarm_while_armed_home
    alias: "Alarm: Trigger when armed home"
    trigger:
    - entity_id: group.perimeter_detectors
      platform: state
      to: 'on'
    condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_home
    action:
    - entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_trigger
    - entity_id: alarm_control_panel.aarlo_arlo
      service: alarm_control_panel.alarm_trigger
    - service: light.turn_on
      data:
        brightness: '100'
        color_name: red
        entity_id: light.gateway_light_7811dcb7afd1
    - service: light.turn_on
      data:
        brightness: '100'
        color_name: red
        entity_id: light.gateway_light_34ce008c1873


  # notification
  - id: send_notification_when_alarm_triggered
    alias: "Alarm: Send notification when triggered"
    trigger:
    - entity_id: alarm_control_panel.home_alarm
      platform: state
      to: triggered
    action:
    - service: script.presence_notifications_when_alarm_triggered


#
## Alarm Arming
###


  # Automatic away mode when nobody is at home during the day,
  # and not on vacation, and no guest
  - id: away_from_home_away_mode
    alias: "Alarm: Away"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: sensor.current_state
        from: 'home'
        to: 'away'
        for:
          minutes: 5
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d0001a6671d
          click_type: single
    condition:
      - condition: state
        entity_id: sensor.current_state
        state: 'home'          
    action:
      - service: notify.ios_ipierre
        data_template:
          message: >
            Alarm ON
      # Arm 
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.home_alarm
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.aarlo_arlo


  # Turn off automatic away mode
  - alias: 'Alarm: Disarm'
    hide_entity: false
    trigger:
      # - platform: state
      #   # entity_id: sensor.current_state
      #   entity_id: binary_sensor.household_home
      #   from: 'off'
      #   to: 'on'
      - platform: state
        entity_id: sensor.current_state
        from: 'away'
        to: 'home'
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d0001a6671d
          click_type: double
    action:
      - service: notify.ios_ipierre
        data_template:
          message: >
            Alarm OFF (disarmed)
      # Disarm alarm
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.aarlo_arlo
      - service: light.turn_off
        data:
          entity_id: light.gateway_light_7811dcb7afd1
      - service: light.turn_off
        data:
          entity_id: light.gateway_light_34ce008c1873


  # Night Alarm
  - alias: 'Alarm: Night'
    hide_entity: false
    trigger:
      - platform: state
        # entity_id: sensor.current_state
        entity_id: binary_sensor.in_bed
        from: 'off'
        to: 'on'
        for:
          minutes: 3
    condition:
      - condition: state
        entity_id: sensor.current_state
        state: 'home'          
    action:
      - service: notify.ios_ipierre
        data_template:
          message: >
            Alarm: Night Mode (in bed since 3 min)
      # Arm 
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.home_alarm
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.aarlo_arlo

  # Turn off from night mode
  - alias: 'Alarm: Disarm From Night Mode'
    hide_entity: false
    trigger:
      - platform: state
        # entity_id: sensor.current_state
        entity_id: binary_sensor.in_bed
        from: 'on'
        to: 'off'
        for:
          minutes: 3
    condition:
      - condition: state
        entity_id: sensor.current_state
        state: 'home'          
    action:
      - service: notify.ios_ipierre
        data_template:
          message: >
            Alarm OFF (from night mode)
      # Disarm alarm
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.aarlo_arlo





#
## Alerts
###

alert:

  alarm:
    name: Alarm Triggered
    message: "Alarm Triggered!"
    done_message: "Alarm Disarmed"
    entity_id: alarm_control_panel.home_alarm
    state: 'triggered'
    repeat: 3
    can_acknowledge: True
    skip_first: False
    notifiers:
      - ios_ipierre