################################################
## Packages / Host / Updates
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'harmony'


    ################################################
    ## Binary Sensor
    ################################################



    ################################################
    ## Sensor
    ################################################

    # sensor.hass_installed_version:
    #   <<: *customize
    #   friendly_name: 'Hass.io Installed Version'
    #   icon: mdi:check-decagram


################################################
## Remote
################################################


remote:
  - platform: harmony
    name: harmony hub
    host: 192.168.0.29
    activity: Regarder la TV


################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      harmony_hub_activity:
        value_template: >
          {% if is_state("remote.harmony_hub", 'on') %}
            {{ states.remote.harmony_hub.attributes.current_activity }}
          {% else %}
            PowerOff
          {% endif %}
################################################
## Input Select
################################################

input_select:
  living_room_tv:
    name: Living Room TV
    options:
      - PowerOff
      - Android TV
      - PS4
      - Écouter de la musique
      - Regarder la TV
      - Regarder Fire TV
      - Regader Netflix
    initial: PowerOff
    icon: mdi:monitor

################################################
## Binary Sensor
################################################

binary_sensor:


################################################
## Automation
################################################

automation:
# The following automation will update the input select when the activity is changed using the harmony remote or other device
  - alias: 'Remote: external update (living room)'
    trigger:
      platform: state
      entity_id: remote.living_room_tv
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.living_room_tv
        option: >
          {{ states.remote.living_room_tv.attributes.current_activity }} 

  # The last automation will start an activity once it’s selected from the input select in the frontend

  - alias: 'Remote: start activity from input select (living room tv)'
    trigger:
      platform: state
      entity_id: input_select.living_room_tv
    action:
      service: script.turn_on
      entity_id: script.input_select_harmony

  # Harmony Monitor  
  - alias: Harmony monitor
    trigger:
      platform: state
      entity_id: remote.harmony_hub
      to: 'unavailable'
    action:
      - service: persistent_notification.create
        data_template:
          title: "Harmony Sync"
          message: >
            Harmony is {{ states('remote.harmony_hub') }}, trying to sync
      - service: remote.harmony_sync
        entity_id: remote.harmony_hub

################################################
## Switch
################################################
switch:
  - platform: template
    switches:
      harmony_tv:
        friendly_name: TV
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Regarder la TV') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: 'Regarder la TV'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: 'PowerOff'

  - platform: template
    switches:
      harmony_music:
        friendly_name: Musique
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Ecouter de la musique') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: '\u00c9couter de la musique'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: 'PowerOff'

    # "Activities": {
    #     "-1": "PowerOff",
    #     "27280319": "Regarder la TV",
    #     "27416411": "PS4",
    #     "27823405": "\u00c9couter de la musique",
    #     "28312619": "Android TV",
    #     "34843663": "Regarder Netflix",
    #     "36560571": "Regarder Fire TV"
    # },

  - platform: template
    switches:
      harmony_ps4:
        friendly_name: PS4 
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'PS4') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: 'PS4'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: 'PowerOff'

  - platform: template
    switches:
      harmony_netflix:
        friendly_name:  Netflix
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Netflix') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: 'Netflix'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: 'PowerOff'

  - platform: template
    switches:
      harmony_fire_tv:
        friendly_name:  Fire TV
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Regarder Fire TV') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: 'Regarder Fire TV'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: 'PowerOff'


################################################
## Script
################################################

# the following script can replace the section of scripts to activate each activity

script:
  input_select_harmony:
    alias: "Start activity from input select"
    sequence:
      - service: remote.turn_on
        data_template:
          entity_id: remote.living_room_tv
          activity: >
            {% if is_state("input_select.living_room_tv", "PowerOff") %}
                -1
            {% elif is_state("input_select.living_room_tv", "Android TV") %}
                28312619
            {% elif is_state("input_select.living_room_tv", "PS4") %}
                27416411
            {% elif is_state("input_select.living_room_tv", "Écouter de la musique") %}
                27823405
            {% elif is_state("input_select.living_room_tv", "Regarder la TV") %}
                27280319           
            {% elif is_state("input_select.living_room_tv", "Regarder Fire TV") %}
                36560571
            {% elif is_state("input_select.living_room_tv", "Netflix") %}
                34843663                
            {% endif %} 

