homeassistant:
  customize:
    sensor.podcast_bbc_minute:
      friendly_name: Latest BBC Minute Episode
    sensor.podcast_daily_tech_news_show:
      friendly_name: Latest Daily Tech News Show Episode
    sensor.podcast_radiofrance:
      friendly_name: Journal de 9h Radio France
    sensor.podcast_journal_francemusique:
      friendly_name: Journal de 8h France Musique
    sensor.podcast_nrj_infos:
      friendly_name: INFOS, METEO et TRAFIC de NRJ Lille 

group:
  podcasts:
    name: Podcasts
    entities:
      - sensor.podcast_bbc_minute
      # - sensor.podcast_daily_tech_news_show
      # - sensor.podcast_radiofrance
      - sensor.podcast_infos_nrj
      - sensor.podcast_nrj_horoscope_taureau
      - sensor.podcast_nrj_horoscope_balance

sensor:
  - platform: scrape
    resource: http://wsrss.bbc.co.uk/bizdev/bbcminute/bbcminute.rss
    name: podcast_bbc_minute
    select: 'enclosure:nth-of-type(1)'
    attribute: url
    scan_interval: 900

  # - platform: scrape
  #   resource: http://feeds.feedburner.com/DailyTechNewsShow
  #   name: podcast_daily_tech_news_show
  #   select: 'enclosure:nth-of-type(1)'
  #   attribute: url
  #   scan_interval: 1800
  
  # - platform: scrape
  #   resource: https://radiofrance-podcast.net/podcast09/rss_10058.xml
  #   name: podcast_radiofrance
  #   select: 'enclosure:nth-of-type(1)'
  #   attribute: url
  #   scan_interval: 900

  # - platform: scrape
  #   resource: https://radiofrance-podcast.net/podcast09/rss_16884.xml
  #   name: podcast_journal_francemusique
  #   select: 'enclosure:nth-of-type(1)'
  #   attribute: url
  #   scan_interval: 900

  # https://www.listennotes.com/podcasts/lhoroscope-nrj-nrj-france-r-ucPF9ydf7/

  - platform: scrape
    resource: https://aod.nrjaudio.fm/xml/2019.xml
    name: podcast_nrj_infos
    select: 'enclosure:nth-of-type(1)'
    attribute: url
    scan_interval: 900

  - platform: scrape
    resource: https://aod.nrjaudio.fm/xml/1994.xml
    name: podcast_nrj_horoscope_taureau
    select: 'enclosure'
    index: 1
    attribute: url
    scan_interval: 900

  - platform: scrape
    resource: https://aod.nrjaudio.fm/xml/1994.xml
    name: podcast_nrj_horoscope_balance
    select: 'enclosure'
    index: 11
    attribute: url
    scan_interval: 900



# entity_id: media_player.google_home_salon
# media_content_id: "http://rf.proxycast.org/1637984354997116928/10058-14.11.2019-ITEMA_22202931-0.mp3"
# media_content_type: music